"""Minimal PDF generator. Hand-rolled — no third-party deps.

Produces a 1-page PDF with bold title + body lines using Helvetica.
Good enough for demo: investor opens the PDF and sees a real document.
"""
from __future__ import annotations

import os
from pathlib import Path


def _escape(text: str) -> str:
    return text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def make_pdf(title: str, lines: list[str]) -> bytes:
    safe_title = _escape(title)
    safe_lines = [_escape(line) for line in lines]

    content_stream_parts: list[str] = ["BT", "/F1 22 Tf", "50 760 Td", f"({safe_title}) Tj", "/F1 11 Tf"]
    for line in safe_lines:
        content_stream_parts.append("0 -22 Td")
        content_stream_parts.append(f"({line}) Tj")
    content_stream_parts.append("ET")
    content_stream = "\n".join(content_stream_parts).encode("latin-1", errors="replace")

    obj1 = b"<< /Type /Catalog /Pages 2 0 R >>"
    obj2 = b"<< /Type /Pages /Count 1 /Kids [3 0 R] >>"
    obj3 = (
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>"
    )
    obj4 = (
        f"<< /Length {len(content_stream)} >>\nstream\n".encode("latin-1")
        + content_stream
        + b"\nendstream"
    )
    obj5 = b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"

    pdf = b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n"
    offsets: list[int] = [0]
    for i, body in enumerate([obj1, obj2, obj3, obj4, obj5], start=1):
        offsets.append(len(pdf))
        pdf += f"{i} 0 obj\n".encode("latin-1") + body + b"\nendobj\n"

    xref_off = len(pdf)
    pdf += b"xref\n0 6\n0000000000 65535 f \n"
    for off in offsets[1:]:
        pdf += f"{off:010d} 00000 n \n".encode("latin-1")
    pdf += f"trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n{xref_off}\n%%EOF\n".encode("latin-1")
    return pdf


def write_demo_pdfs(static_dir: Path) -> None:
    static_dir.mkdir(parents=True, exist_ok=True)

    files = [
        (
            "refi_demo.pdf",
            "LeaseAI - Refinancer Package",
            [
                "Deal: D-2026-0001",
                "Client: Globex Inc. (SIREN 123456789)",
                "Partner: Tech Solutions Partner",
                "Amount financed: 85 500.00 EUR",
                "Duration: 36 months",
                "Indicative monthly payment: see API",
                "Risk band: A (score 82)",
                "Decision requested: Approve / Reject / Clarification",
                "",
                "Summary auto-generated by LeaseAI demo backend.",
            ],
        ),
        (
            "contract_demo.pdf",
            "LeaseAI - Contract Draft",
            [
                "Contract: C-2026-0001",
                "Lessor: LeaseAI",
                "Lessee: Globex Inc.",
                "Asset value: 85 500.00 EUR",
                "Duration: 36 months",
                "Frequency: monthly",
                "Status: draft - awaiting signature",
                "",
                "This is a demo document.",
            ],
        ),
        (
            "invoice_demo.pdf",
            "LeaseAI - Invoice",
            [
                "Invoice number: INV-2026-0001",
                "Lessee: Globex Inc.",
                "Period: 2026-05-01 -> 2026-05-31",
                "Amount excl. tax: 2 175.00 EUR",
                "VAT 20%: 435.00 EUR",
                "Amount incl. tax: 2 610.00 EUR",
                "Due date: 2026-05-15",
            ],
        ),
        (
            "offer_demo.pdf",
            "LeaseAI - Firm Offer",
            [
                "Offer: O-2026-0001",
                "Client: Globex Inc.",
                "Amount: 85 500.00 EUR",
                "Duration: 36 months",
                "Monthly payment: see API",
                "Valid until: 2026-06-15",
            ],
        ),
        (
            "sepa_demo.pdf",
            "LeaseAI - SEPA Mandate",
            [
                "Mandate ref: SEPA-2026-0001",
                "Debtor: Globex Inc.",
                "IBAN: FR76 **** **** **** **** **42",
                "Creditor: LeaseAI",
                "Type: Recurring",
                "Status: signed (mock)",
            ],
        ),
        (
            "delivery_demo.pdf",
            "LeaseAI - PV Livraison",
            [
                "Delivery note: PV-2026-0001",
                "Lessee: Globex Inc.",
                "Items delivered: 71 units",
                "Delivered on: 2026-05-08",
                "Acknowledged by: Sophie Client",
                "Status: confirmed (mock)",
            ],
        ),
    ]

    for fname, title, lines in files:
        path = static_dir / fname
        if not path.exists() or os.environ.get("REGEN_DEMO_PDFS") == "1":
            path.write_bytes(make_pdf(title, lines))
